### ISSUE TITLE
Thousands of error messages in the webserver logs

### ISSUE THREAD

**Issue by RuSc** [lebowski42/dokuwiki-authorlist#1]
Even though the plugin itself is working great, it is generating thousands of error messages in my webserver logs. I'm guessing it's just one error message for every page load.

Like said; the plugin seems to work fine and error messages are not visible to visitors or users, but they're making my logfiles hard to read and unnecessary large. Any idea what's it about? It's the exact same error repeated over and over again:

[06-May-2013 22:02:58 Europe/Helsinki] PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /home/edstari/public_html/wiki/lib/plugins/authorlist/helper.php on line 137

**Comment by lebowski42** [comment]
Hi,

can you have a look to the php-files in lib/plugins/authorlist if there is any file containing 
   error_reporting (E_ALL | E_STRICT)
I pushed one version to git, where i forgot to delete this line. Maybe you got this one.

Can you have a look, if you get only warning from /home/edstari/public_html/wiki/lib/plugins/...-files, or if you get  warings from everywhere. 
i put a new version to the git-repo which corrects the error you posted.

Thanks,
