### ISSUE TITLE
It conflicts with the plugin 'markdowku'.

### ISSUE THREAD

**Issue by ToroLiu** [lebowski42/dokuwiki-authorlist#2]
I use the [markdowku](https://www.dokuwiki.org/plugin:markdowku) plugin to enable `markdown` syntax. And the `authorlist` plugin conflicts with that. It will lead the `markdown` invalid behavior.

**Comment by lebowski42** [comment]
Hi,

i tried markdowku but i can't see any conflict. Can you give some information how to reproduce the invalid behavior?

**Comment by ToroLiu** [comment]
Sorry, it seems my fault about invalid syntax. I try again and don't know
how to reproduce it now. I have stopped the authorlist plugin.

2013/5/27 lebowski42 notifications@github.com
