### ISSUE TITLE
Authorlist conflict with search box

### ISSUE THREAD

**Issue by tosmatt** [lebowski42/dokuwiki-authorlist#3]
When I checked  authorlist in plugin manger panel,search box can not work.
I just created a wiki, and the "Search" function never finds anything but jump into a newpage.  I created some pages in some pagespaces, so I know the text is there. 
When I uncheck authorlist in plugin manger panel,the "Search" function can work well.

**Comment by lebowski42** [comment]
Hi,
 i can't reproduce this error. Do you mean the default dokuwiki searchbox?

Which DokuWiki version do you use? Is there any logentry? Can you please enable 'allowdebug' in config-manager and show me the output of <url-of-my-page>...?do=debug

Thanks

**Comment by tosmatt** [comment]
Sorry I forget the detail for you. This the detail for my setting.
1.Dokuwiki Version:Dokuwiki-2013-05-10.tgz “Weatherwax”
2.Do you mean the default dokuwiki searchbox? Yes.
3.Can you please enable 'allowdebug' in config-manager and show me the output of ...?do=debug.
This is the log but very long(I'm using chinese).
When reporting bugs please send all the following output as a mail to andi@splitbrain.org The best way to do this is to save this page in your browser

$INFO:
Array
(
    [id] => test
    [rev] => 0
    [isadmin] => 1
    [ismanager] => 1
    [userinfo] => ***
    [perm] => 255
    [subscribed] => 
    [client] => dql
    [namespace] => 
    [locked] => 
    [filepath] => J:/Program Files/Apache2.2/htdocs/data/pages/test.txt
    [exists] => 
    [writable] => 1
    [editable] => 1
    [lastmod] => 
    [meta] => Array
        (
        )

```
[ip] => 
[user] => 
[sum] => 
[editor] => 
[ismobile] => 
```

)
$_SERVER:
Array
(
    [HTTP_HOST] => localhost:8080
    [HTTP_CONNECTION] => keep-alive
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.94 Safari/537.36
    [HTTP_ACCEPT_ENCODING] => gzip,deflate,sdch
    [HTTP_ACCEPT_LANGUAGE] => zh-CN,zh;q=0.8
    [HTTP_COOKIE] => DW0b7b8d3cdc8453fc824e93b4785173f8=bGl1ZHE%3D%7C1%7CMFVicVk3VjdmbG5VTFJHM1RzS2hDZz09; DOKU_PREFS=aceeditor%23on%23list%23thumbs; DokuWiki=7c3ip3k35qatdrg0obqv1jikg2; favoris[wiki:syntax]=1%3B1370146041; favoris[淇敼灞ュ巻]=5%3B1370146130; coindexmenu_2326551ab28f6d8801=1; coindexmenu_2867851ab28f76b221=1; coindexmenu_1402351ab291a29f1b=; coindexmenu_946051ab291abc315=; coindexmenu_26251ab295017a78=1; coindexmenu_1470351ab2a33aae0d=; coindexmenu_1694151ab2a6dda90d=; coindexmenu_3217651ab2aaf278ba=1; csindexmenu_3217651ab2aaf278ba=2; favoris[rtx璁板綍:rtx璁板綍]=1%3B1370172366; favoris[闂鐩稿叧:闂鍏遍€氭牸寮廬=3%3B1370172385; csindexmenu_2232451ab2a1ea7693=48; favoris[绗旇鏈�:绗旇鏈琞=1%3B1370174152; favoris[缁忛獙闆嗚悆:缁忛獙闆嗚悆]=1%3B1370174158; favoris[sidebar]=48%3B1370174202; favoris[浜嬮」鍛ㄧ煡:ccm]=5%3B1370174217; favoris[浜嬮」鍛ㄧ煡:h1]=4%3B1370174235; favoris[浜嬮」鍛ㄧ煡:閭欢涔﹀啓瑙勮寖]=4%3B1370174256; favoris[浜嬮」鍛ㄧ煡:rest]=4%3B1370174276; favoris[浜嬮」鍛ㄧ煡:娴嬭瘯娉ㄦ剰浜嬮」]=4%3B1370174292; favoris[浜嬮」鍛ㄧ煡:鏈烘埧绠＄悊鏉′緥]=4%3B1370174317; favoris[浜嬮」鍛ㄧ煡:甯哥敤鏈嶅姟鍣ㄥ湴鍧€鍒楄〃]=4%3B1370174334; favoris[浜嬮」鍛ㄧ煡:澶у濂絔=4%3B1370174350; favoris[瀹炴満鎿嶄綔:杩涘叆debug妯″紡鐨勪笁绉嶆柟寮廬=5%3B1370174390; favoris[瀹炴満鎿嶄綔:system-install]=6%3B1370174408; favoris[瀹炴満鎿嶄綔:swf鏂板崱涓嶈兘姝ｅ父绔欑珛鐨勫鐞哴=4%3B1370174431; favoris[瀹炴満鎿嶄綔:鐢眒cpu1鐧诲綍鍒板悇鍗＄殑鏂规硶]=4%3B1370174450; favoris[寮忔牱瀛︿範:oam:etheroam甯ф牸寮廬=4%3B1370174486; favoris[寮忔牱瀛︿範:oam:h3]=4%3B1370174540; favoris[寮忔牱瀛︿範:oam:x]=4%3B1370174559; favoris[绗旇鏈�:xq]=4%3B1370174588; favoris[绗旇鏈�:dql]=4%3B1370174608; favoris[绗旇鏈�:qa-rtx]=4%3B1370174626; favoris[绗旇鏈�:jirj]=4%3B1370174642; favoris[绗旇鏈�:mq]=4%3B1370174658; favoris[缁忛獙闆嗚悆:鍏遍€氶棶棰�:纭欢鐘舵€佸拰鏁版嵁搴撲笉涓€鑷碷=4%3B1370174679; favoris[缁忛獙闆嗚悆:璀︽姤鍙戠敓:瑁呯疆鍐呯洃瑙哴=4%3B1370174725; favoris[缁忛獙闆嗚悆:璀︽姤鍙戠敓:lan]=4%3B1370174744; favoris[缁忛獙闆嗚悆:璀︽姤鍙戠敓:lan寮傚父鍙戠敓]=4%3B1370174762; favoris[缁忛獙闆嗚悆:闈為棶棰樹竴瑙堣〃]=4%3B1370174779; favoris[rtx璁板綍:test]=4%3B1370174812; csindexmenu_20=18; favoris[wiki:wiki]=1%3B1370174849; coindexmenu_20=1.3.5.6.7.9.10.11.13; favoris[寮忔牱瀛︿範:寮忔牱瀛︿範]=2%3B1370181067; favoris[jiang]=1%3B1370181075; favoris[j]=1%3B1370181084; favoris[hello]=1%3B1370181095; favoris[瑕乚=3%3B1370181120; favoris[鐣橾=1%3B1370181204; favoris[鐣欎笅]=1%3B1370181207; favoris[浜嬮」鍛ㄧ煡:閮芥斁鍒癩=1%3B1370181312; favoris[瀹炴満鎿嶄綔:瀹炴満鎿嶄綔]=1%3B1370181322; favoris[閫夋嫨鍒嗙被]=1%3B1370181327; favoris[璇硶]=1%3B1370181413; favoris[tets]=1%3B1370181466; favoris[dfdf]=1%3B1370182122; favoris[kl]=2%3B1370182382; favoris[鐭ヨ瘑]=3%3B1370182436; favoris[t]=1%3B1370182678; favoris[ts]=1%3B1370182729; favoris[df]=1%3B1370182952; favoris[浜嬮」鍛ㄧ煡:浜嬮」鍛ㄧ煡]=3%3B1370183981; favoris[浜嬮」鍛ㄧ煡:test]=1%3B1370183988; favoris[dfd]=8%3B1370215114; favoris[鐭ヨ瘑搴撻椤礭=231%3B1370215321; favoris[test]=2%3B1370215326
    [PATH] => H:\Windows\system32;H:\Windows;H:\Windows\System32\Wbem;H:\Windows\System32\WindowsPowerShell\v1.0\;J:\Program Files\php;H:\Program Files\TortoiseSVN\bin
    [SystemRoot] => H:\Windows
    [COMSPEC] => H:\Windows\system32\cmd.exe
    [PATHEXT] => .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
    [WINDIR] => H:\Windows
    [SERVER_SIGNATURE] => 
    [SERVER_SOFTWARE] => Apache/2.2.22 (Win32) PHP/5.4.15
    [SERVER_NAME] => localhost
    [SERVER_ADDR] => 127.0.0.1
    [SERVER_PORT] => 8080
    [REMOTE_ADDR] => 127.0.0.1
    [DOCUMENT_ROOT] => J:/Program Files/Apache2.2/htdocs
    [SERVER_ADMIN] => test@hotmail.com
    [SCRIPT_FILENAME] => J:/Program Files/Apache2.2/htdocs/doku.php
    [REMOTE_PORT] => 49634
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => do=search&id=Test&do=debug
    [REQUEST_URI] => /doku.php?do=search&id=Test&do=debug
    [SCRIPT_NAME] => /doku.php
    [PHP_SELF] => /doku.php
    [REQUEST_TIME_FLOAT] => 1370215329.515
    [REQUEST_TIME] => 1370215329
    [REMOTE_USER] => dql
)
$conf:
Array
(
    [title] => 鐭ヨ瘑搴�
    [start] => 鐭ヨ瘑搴撻椤�
    [lang] => zh
    [template] => dokuwiki
    [tagline] => 鏋勫缓闀夸箙鐨勫垎浜満鍒讹紝灏濊瘯鎸佺画鐨勭煡璇嗙粡钀ャ€�
    [sidebar] => sidebar
    [license] => 0
    [savedir] => ./data
    [basedir] => 
    [baseurl] => 
    [cookiedir] => 
    [dmode] => 493
    [fmode] => 420
    [allowdebug] => 1
    [recent] => 20
    [recent_days] => 7
    [breadcrumbs] => 10
    [youarehere] => 0
    [fullpath] => 0
    [typography] => 1
    [dformat] => %Y/%m/%d %H:%M
    [signature] =>  --- //[[@MAIL@|@NAME@]] @DATE@//
    [showuseras] => loginname
    [toptoclevel] => 1
    [tocminheads] => 3
    [maxtoclevel] => 3
    [maxseclevel] => 3
    [camelcase] => 0
    [deaccent] => 1
    [useheading] => 0
    [sneaky_index] => 0
    [hidepages] => 
    [useacl] => 1
    [autopasswd] => ***
    [authtype] => ***
    [passcrypt] => ***
    [defaultgroup] => user
    [superuser] => @admin
    [manager] => !!not set!!
    [profileconfirm] => 1
    [rememberme] => 1
    [disableactions] => 
    [auth_security_timeout] => ***
    [securecookie] => 1
    [remote] => 0
    [remoteuser] => !!not set !!
    [usewordblock] => 1
    [relnofollow] => 1
    [indexdelay] => 432000
    [mailguard] => ***
    [iexssprotect] => 1
    [usedraft] => 1
    [htmlok] => 0
    [phpok] => 0
    [locktime] => 900
    [cachetime] => 86400
    [target] => Array
        (
            [wiki] => 
            [interwiki] => 
            [extern] => 
            [media] => 
            [windows] => 
        )

```
[mediarevisions] => 1
[refcheck] => 1
[refshow] => 0
[gdlib] => 2
[im_convert] => 
[jpg_quality] => 70
[fetchsize] => 0
[subscribers] => 0
[subscribe_time] => 86400
[notify] => ***
[registernotify] => ***
[mailfrom] => ***
[mailprefix] => ***
[htmlmail] => ***
[sitemap] => 0
[rss_type] => rss1
[rss_linkto] => diff
[rss_content] => abstract
[rss_media] => both
[rss_update] => 300
[rss_show_summary] => 1
[updatecheck] => 1
[userewrite] => 0
[useslash] => 0
[sepchar] => _
[canonical] => 0
[fnencode] => url
[autoplural] => 0
[compression] => gz
[gzip_output] => 0
[compress] => 1
[cssdatauri] => 0
[send404] => 0
[broken_iua] => 0
[xsendfile] => 0
[renderer_xhtml] => xhtml
[readdircache] => 0
[dnslookups] => 1
[proxy] => ***
[safemodehack] => 0
[ftp] => ***
[plugin] => Array
    (
        [addnewpage] => Array
            (
                [addpage_exclude] => wiki;绗旇鏈�
                [addpage_showroot] => 0
                [addpage_hide] => 0
                [addpage_hideACL] => 1
            )

        [authorlist] => ***
        [editx] => Array
            (
                [user_rename] => xq,dql,,mq,fu
                [user_rename_nr] => xq,dql,,mq,fu
                [user_delete] => xq,dql,,mq,fu
            )

        [indexmenu] => Array
            (
                [headpage] => 
                [only_admins] => 0
                [aclcache] => groups
                [hide_headpage] => 1
                [page_index] => 
                [empty_msg] => 
                [skip_index] => 
                [skip_file] => 
                [show_sort] => 1
                [themes_url] => http://samuele.netsons.org/dokuwiki
                [be_repo] => 
                [sneaky_index] => 0
            )

    )

[fperm] => 420
[datadir] => J:/Program Files/Apache2.2/htdocs/data/pages
[olddir] => J:/Program Files/Apache2.2/htdocs/data/attic
[mediadir] => J:/Program Files/Apache2.2/htdocs/data/media
[mediaolddir] => J:/Program Files/Apache2.2/htdocs/data/media_attic
[metadir] => J:/Program Files/Apache2.2/htdocs/data/meta
[mediametadir] => J:/Program Files/Apache2.2/htdocs/data/media_meta
[cachedir] => J:/Program Files/Apache2.2/htdocs/data/cache
[indexdir] => J:/Program Files/Apache2.2/htdocs/data/index
[lockdir] => J:/Program Files/Apache2.2/htdocs/data/locks
[tmpdir] => J:/Program Files/Apache2.2/htdocs/data/tmp
[changelog] => J:/Program Files/Apache2.2/htdocs/data/meta/_dokuwiki.changes
[media_changelog] => J:/Program Files/Apache2.2/htdocs/data/meta/_media.changes
[mailfromnobody] => ***
```

)
DOKU_BASE:
/
abs DOKU_BASE:
http://localhost:8080/
rel DOKU_BASE:
/
PHP Version:
5.4.15
locale:
C
encoding:
utf-8
Auth backend capabilities:

Fatal error:  Cannot access protected property auth_plugin_authplain::$cando in J:\Program Files\Apache2.2\htdocs\inc\html.php on line 1606

**Comment by lebowski42** [comment]
Hi,
i tried the same settings than you, but i can't reproduce the error. Do you tried it again? Maybe you got this error because of something else, and it disappear, because you saved the plugin settings, this means e.g. the cache was rebuild. 
Try the searchindex plugin to rebuild the index, which is used for searching:

**Comment by tosmatt** [comment]
I tried the searchindex plugin but it still can not fix the problem.

**Comment by lebowski42** [comment]
Hi,
the only problem can be the action-plugin comes with the authorlist plugin. Please move the file action.php inside lib/plugins/authorlist to somewhere else and try it again.

**Comment by tosmatt** [comment]
Yes yes,I do what you said.I move the file action.php inside lib/plugins/authorlist to somewhere else and this problem was solved.Thank you very much.I don't know why this problem occurred,but I still want to use your plugin.so anyway...
^_^
Will other problem occur without action.php?

**Comment by lebowski42** [comment]
Hi,

the action.php is used, if you checked "Authorlist on every page by default?" in config. So without, you have to add it manually to every page, using ~AUTHORS~ on this page.

**Comment by tosmatt** [comment]
Thank you for your answer!
